### PR TITLE
add aol sucks gif

### PR DESCRIPTION
**Pull request by pilz0**

### CODE REVIEW

**Review by Dishpit — CHANGES_REQUESTED** [review]
made redundant by #19 

maybe we can change it up a bit? or add some more 88x31s?

also merge conflicts

**Comment by Alfredooe** [comment]
please throw some time in my calendar to discuss this change 

image

**Comment by pilz0** [comment]
> @pilz0 please throw some time in my calendar to discuss this change
> 
> image

grafik

**Comment by pilz0** [comment]
> made redundant by #19
> 
> maybe we can change it up a bit? or add some more 88x31s?
> 
> also merge conflicts
yes im going to make a new one

**Pull request closed without merging**
