### PR TITLE
Add Embr Web IDE

### PR DESCRIPTION
**Pull request by alamshafil**
This PR adds support for Embr, an advanced programming language, in the browser! This magic is possible by WASM. 

The page at `/embr` includes a Web IDE to run, learn, and play with Embr!

### CODE REVIEW

**Comment by Dishpit** [comment]
looks super cool! couple things:

running embr code results in this error in the browser console, with no code ran

image

Also could we get some lightmode in here?

image

**Review by Dishpit — CHANGES_REQUESTED** [review]
(see prev comment)

**Comment by alamshafil** [comment]
Ok I updated the code, hope it works! It worked fine on my local server, not sure why it was giving you an error. Let me know if it works now.

**Comment by Dishpit** [comment]
> Ok I updated the code, hope it works! It worked fine on my local server, not sure why it was giving you an error. Let me know if it works now.

no longer getting that error in the browser console, but now i'm seeing this in the ide terminal
image

**Comment by alamshafil** [comment]
That is odd, I see this:
Screenshot 2024-12-29 at 12 56 00 PM

Is it having trouble loading the .js or .wasm file? It could be some server config. It should not be due to CORS since the files are in the same domain.

Also feel free to squash my commits into a single one since I had to fix the merge conflict - keeps the git history clean :)

**Comment by Dishpit** [comment]
could honestly just be bcuz my machine, or the preview environment

gonna yolo merge it and we can diagnose any bugs later

**Pull request merged**
