### PR TITLE
🛡Add protection against accidentally typing forbidden words🛡

### PR DESCRIPTION
**Pull request by whybazinga**
We don't want anyone accidentally typing THAT word in one of the inputs and the going to HELL, do we?

### CODE REVIEW

**Comment by ItsNyoty** [comment]
Should change it to ohio, cuz we don't talk about it...

**Review by Dishpit — APPROVED** [review]

**Comment by Dishpit** [comment]
merge conflicts, pls fix <3

**Comment by Dishpit** [comment]
got some more conflicts lmao

**Comment by whybazinga** [comment]
💅💁🏳️‍🌈👣

**Pull request merged**
