### PR TITLE
Comment Section

### PR DESCRIPTION
**Pull request by 0xivb**
image

Before merging you'll need to create a neon DB in Vercel (it will only take a few seconds):
image
image
image

the default config vercel provides is perfect and it will automatically define all the variables necessary;
it should also automatically run migrations upon deployment, but if there are any issues mention me and I'll help out

I've also added docs for local dev

---
p.s. I saw that someone else added a chat thing, but the backend was hosted on a third party server - this uses vercel functions / storage since this is hosted on Vercel.

### CODE REVIEW

**Comment by 0xivb** [comment]
you can try this rn here: https://slopify-0xivb.vercel.app/#comments-title

**Comment by Dishpit** [comment]
gonna hold off on db and server req's for the time being, so closing this for now

got some things i wanna cook up initially that use db/server and will make this process a bit more seamless w everything else

**Comment by 0xivb** [comment]
> gonna hold off on db and server req's for the time being, so closing this for now
> 
> got some things i wanna cook up initially that use db/server and will make this process a bit more seamless w everything else

this uses a vercel function so it should work with your current setup right out of the box, no additional server required

**Comment by Dishpit** [comment]
> > gonna hold off on db and server req's for the time being, so closing this for now
> > got some things i wanna cook up initially that use db/server and will make this process a bit more seamless w everything else
> 
> this uses a vercel function so it should work with your current setup right out of the box, no additional server required

good point; lemme look dig into it further rq

**Comment by Dishpit** [comment]
okay dug into it and miiiight have to just put a comment box on pause for the time being; with the amount of traffic the site's getting, it'll blow the usage limits (and my wallet) out of the water lmao

**Comment by 0xivb** [comment]
fair enough 👍🏻

**Pull request closed without merging**
