### PR TITLE
Small refactor

### PR DESCRIPTION
**Pull request by MDMCK10**
Just a few changes here and there, nothing too major

### CODE REVIEW

**Comment by Dishpit** [comment]
merge conflicts, pls fix <3

**Comment by MDMCK10** [comment]
oh my god each time i fix it like 5 more pull requests appear make it stop

**Comment by MDMCK10** [comment]
> merge conflicts, pls fix <3

done... i think.

**Comment by MDMCK10** [comment]
damn it

**Comment by Dishpit** [comment]
> > merge conflicts, pls fix <3
> 
> @Dishpit done... i think.

got a couple more @MDMCK10, i'm so sorry lmao

**Pull request merged**
