### PR TITLE
chat dark mode and buttons old

### PR DESCRIPTION
**Pull request by duck4i**
Something like this? 

image

### CODE REVIEW

**Comment by infernostars** [comment]
can we theme the chatbox to make. sense

**Comment by Dishpit** [comment]
merge conflicts need repair

**Comment by duck4i** [comment]
Let me just fix the @infernostars retro wishes and I'll do that :)

**Comment by duck4i** [comment]
> can we theme the chatbox to make. sense otherwise i will be ☹️

Is this what you meant? Better? Needs more? 
image

**Comment by infernostars** [comment]
the outlinefeels inconsistent but yeah thats the vibe

**Comment by infernostars** [comment]
> the outlinefeels inconsistent but yeah thats the vibe

probably cuz its 1px and the button's 2px

**Comment by infernostars** [comment]
> [...]
> like this?

bottom and right side is too bright [maybe change to be the same as button top sides?] but yeah thats good

**Comment by infernostars** [comment]
also arguably the button fonts are inconsistent to the rest of the chat but that's also sort of the point? so hmm

**Comment by Dishpit** [comment]
i love how we went from pure 100% slop to actually being mindful and producing GOOD slop

this is amazing

**Comment by duck4i** [comment]
> > [...]
> > like this?
> 
> bottom and right side is too bright [maybe change to be the same as button top sides?] but yeah thats good

happy? 
image

**Comment by infernostars** [comment]
lgtm

**Comment by duck4i** [comment]
> also arguably the button fonts are inconsistent to the rest of the chat but that's also sort of the point? so hmm

Monospace all? or nah? 
image

**Comment by infernostars** [comment]
maybe smaller row buttons and send should be bold?

**Comment by infernostars** [comment]
if that doesnt work then nah /shrug

**Comment by Dishpit** [comment]
> > also arguably the button fonts are inconsistent to the rest of the chat but that's also sort of the point? so hmm
> 
> Monospace all? or nah? image

i'm a slut for monospaced fonts

**Comment by infernostars** [comment]
don't merge until quick color fix

**Comment by infernostars** [comment]
lgtm, merge? [we should fix blink seperately imo, since it maybe should be redesigned a bit anyway]

**Pull request merged**
