### PR TITLE
add pussy

### PR DESCRIPTION
**Pull request by ItsNyoty**

### CODE REVIEW

**Comment by ItsNyoty** [comment]
Creds to @zepje for creating the poeskat printer

**Review by Dishpit — CHANGES_REQUESTED** [review]
very cool, but can we get an english variant of this?

the majority of Slopify users are likely english speakers
image

**Comment by Zepje** [comment]
updated 👍

**Comment by ItsNyoty** [comment]
It's updated by @Zepje to English 👍

**Review by Dishpit — APPROVED** [review]
love it

**Pull request merged**
