### PR TITLE
add much more clear slopchat button

### PR DESCRIPTION
**Pull request by Nasko-5**
yeah, 
um there's a bunch of errors in index.html for some reason?? not sure what those are about, they came with the most recent code i had pulled

### CODE REVIEW

**Comment by infernostars** [comment]
can you send an image of the change that is a huge pr lmao

**Comment by Nasko-5** [comment]
what the fuck happened

**Comment by Nasko-5** [comment]
uhhh, okay.. it should just be this @infernostars 
image

**Comment by infernostars** [comment]
i meant can you send a. preview

**Comment by Nasko-5** [comment]
image

**Comment by Nasko-5** [comment]
wtf how do i deal with these merge conflicts?

**Comment by Nasko-5** [comment]
ok nvm im closing this and making a new thing

**Pull request closed without merging**
