### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by DankoF-industries**
Added ultrakill gif

### CODE REVIEW

**Review by Dishpit — APPROVED** [review]
has merge conflicts, pls fix <3

**Comment by DankoF-industries** [comment]
Now it should work

вт, 31 груд. 2024 р. о 17:09 Dishpit ***@***.***> пише:

**Comment by Dishpit** [comment]
still got a couple more, i'm so sorry lmao

**Review by Dishpit — CHANGES_REQUESTED** [review]
prev comment

**Pull request closed without merging**
