### PR TITLE
Let Elon fly!

### PR DESCRIPTION
**Pull request by gyuheon0h**
I've always wanted to fly like Elon. Let's allow users to control Elon as he flies through yellow pipes!
@Dishpit @ronnie-rios

### CODE REVIEW

**Review by Dishpit — APPROVED** [review]
fly, elon! fly!

**Comment by Dishpit** [comment]
oop, got some merge conflicts; @gyuheon0h if you can patch these, i'll merge

**Review by Dishpit — CHANGES_REQUESTED** [review]
merge conflicts

**Comment by gyuheon0h** [comment]
@Dishpit fixed merge conflicts!

**Pull request merged**
