### PR TITLE
Useless Chatbot

### PR DESCRIPTION
**Pull request by zoogies**
Is it really a slop site without an annoying chatbot?

image

### CODE REVIEW

**Comment by zoogies** [comment]
@Dishpit @ronnie-rios

**Comment by ItsNyoty** [comment]
lgtm

**Comment by ronnie-rios** [comment]
At work
Merging via the GitHub app 💀💀💀

**Comment by zoogies** [comment]
😭

**Comment by ronnie-rios** [comment]
Work sucks 🥲, Slopify > work

**Comment by zoogies** [comment]
@ronnie-rios you should quit your day job and go full time slopify. YC spring 2025?? 👀

**Comment by ronnie-rios** [comment]
@zoogies On the roadmap 

Someone make a PR with a YC 2025 banner or something equivalent 💀

**Pull request merged**
