### PR TITLE
world map

### PR DESCRIPTION
**Pull request by zachpinto**
Users can select origin city/state/country and populate world map

### CODE REVIEW

**Comment by zachpinto** [comment]
@Dishpit @ronnie-rios

**Comment by zachpinto** [comment]
Hi there im kinda stupid. How do I set myself as assignee?

**Comment by ronnie-rios** [comment]
this is awesome, if you could review some of the merge conflicts will get this added

**Review by ronnie-rios — CHANGES_REQUESTED** [review]
merge conflicts

**Comment by zachpinto** [comment]
Hey @Dishpit @ronnie-rios could you help me out with the merge conflict?

**Comment by zachpinto** [comment]
Yeah absolutely

**Comment by zachpinto** [comment]
Hey, ftr I opened a new PR.

**Pull request closed without merging**
